### ISSUE TITLE
Erro de teste: user não tem coluna nusp

### ISSUE THREAD

**Issue by andre19980** [Ruhaker/MAC0218#1]
Error:
WelcomeControllerTest#test_should_get_index:
ActiveRecord::Fixture::FixtureError: table "users" has no column named "nusp".

**Comment by lucaby** [comment]
Aparentemente, isto é consertado executando:

`rails db:test:prepare`

**Comment by lucaby** [comment]
O comando

`rails db:test:prepare` 

não tinha resolvido o problema.

O erro estava na existência do "Welcome Controller", que foi deletado
